In [1]:
#Dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [8]:
# Name of the CSV file
AZ_retail_csv = os.path.join('Datasets','AZ Retail Data.csv')

In [9]:
# creating a data frame 
AZ_df = pd.read_csv(AZ_retail_csv) 
AZ_df.head()

,Geo Footnote,Geographic Area Name,2017 NAICS code,2017 NAICS Footnote,Meaning of NAICS code,Year,Number of firms,Number of establishments,"Sales, value of shipments, or revenue ($1,000)","Annual payroll ($1,000)","First-quarter payroll ($1,000)",Number of employees,"Range indicating percent of total sales, value of shipments, or revenue imputed",Range indicating percent of total annual payroll imputed,Range indicating percent of total employees imputed
0400000US04,NaN,Arizona,44-45,NaN,Retail trade,2017,9830,17918,104365600,9505481,2365502,324912,Less than 10%,10% to less than 20%,10% to less than 20%
0400000US04,NaN,Arizona,441,NaN,Motor vehicle and parts dealers,2017,1250,2059,25808220,2192296,534080,44267,Less than 10%,10% to less than 20%,10% to less than 20%
0400000US04,NaN,Arizona,442,NaN,Furniture and home furnishings stores,2017,621,959,2436003,310635,75007,9962,10% to less than 20%,10% to less than 20%,30% to less than 40%
0400000US04,NaN,Arizona,443,NaN,Electronics and appliance stores,2017,304,524,1798437,211244,47338,6436,Less than 10%,30% to less than 40%,20% to less than 30%
0400000US04,NaN,Arizona,444,NaN,Building material and garden equipment and sup...,2017,708,1087,5569365,638354,157251,23621,Less than 10%,Less than 10%,Less than 10%

In [10]:
# Delete extraneous column
AZ_df = AZ_df.drop(columns=['Geo Footnote', '2017 NAICS Footnote', 'id', '2017 NAICS code', 
                            'Annual payroll ($1,000)', 'First-quarter payroll ($1,000)', 
                            'Number of employees', 'Range indicating percent of total annual payroll imputed', 
                            'Range indicating percent of total employees imputed', 
                           ])


AZ_df.head()

KeyError: "['id'] not found in axis"

In [ ]:
AZ_df.loc[AZ_df['Meaning of NAICS code']=='Electronic shopping and mail-order houses', 'eCommerce?']= 1
AZ_df.loc[AZ_df['Meaning of NAICS code']!='Electronic shopping and mail-order houses', 'eCommerce?']= 0

AZ_df.head()

In [ ]:
AZ_df.groupby('eCommerce?')['Sales, value of shipments, or revenue ($1,000)'].sum()

In [ ]:
#Create Pie Chart
labels = "eCommerce", "Retail"
value = [257001507, 2717305378]
colors = ["purple", "grey"]
explode = (0.3,0)

In [ ]:
# Create a pie chart based upon the above data
plt.pie(value, labels=labels, colors=colors, explode=explode,
        autopct="%1.1f%%", shadow=True, startangle=180)
plt.title("eCommerce vs Retail 2017")

# Create axes which are equal so we have a perfect circle
plt.axis("equal")
plt.show()
#plt.savefig("../Images/PyPies.png")

In [ ]:
#Number of Establishments

In [ ]:
AZ_df.loc[AZ_df['Meaning of NAICS code']=='Electronic shopping and mail-order houses', 'eCommerce?']= 1
AZ_df.loc[AZ_df['Meaning of NAICS code']!='Electronic shopping and mail-order houses', 'eCommerce?']= 0

AZ_df.head()

In [ ]:
AZ_df.groupby('eCommerce?')['Number of establishments'].sum()